use_frameworks!

target 'SI1-OTPCustomView_Example' do
  pod 'SI1-OTPCustomView', :git => 'https://github.com/SI-Du/SI1-OTPCustomView', :tag => '0.1.0'

  target 'SI1-OTPCustomView_Tests' do
    inherit! :search_paths

    
  end
end
